### ISSUE TITLE
Can not import the screen file

### ISSUE THREAD

**Issue by xiaoxue999** [pavelnemirovsky/zabbix-redis-template#1]
Cannot find graph "Redis: "{#INSTANCE}" - {#COMMAND} Calls Overview" used in screen "Redis Monitoring: Redis Command Overview".
![1](https://cloud.githubusercontent.com/assets/22721577/21667070/044c1f1c-d331-11e6-83c3-39ef84960953.png)

**Comment by pavelnemirovsky** [comment]
Its basically during an import requires to see first host where all redis graphs already appears.

**Comment by pavelnemirovsky** [comment]
Please close the issue if it is resolves the issue.

**Comment by xiaoxue999** [comment]
OK,it works,thanks...
