### ISSUE TITLE
How to change {$REDIS_PASSWORDS} for everal different srv?

### ISSUE THREAD

**Issue by kksudo** [pavelnemirovsky/zabbix-redis-template#12]
Hello!
I can change {$REDIS_PASSWORDS} for  all templates, but how i can specific setup different password for  others several servers ?
And if password is not correct for new server, discover app redis will not be created

All templates
![image](https://user-images.githubusercontent.com/8701324/44414675-0b0ea300-a577-11e8-8378-35f9c87b64bb.png)

Specific server 
![image](https://user-images.githubusercontent.com/8701324/44414734-3e513200-a577-11e8-954f-95aff82de647.png)

**Comment by pavelnemirovsky** [comment]
Oh u can override this macros on HOST and GROUP level in the same way as its done on template level.  https://www.zabbix.com/documentation/3.0/manual/config/macros/usermacros
