### ISSUE TITLE
Incorrectly identifies redis-cli executable.

### ISSUE THREAD

**Issue by khazhyk** [pavelnemirovsky/zabbix-redis-template#3]
```
$ locate redis-cli
/etc/bash_completion.d/redis-cli
/home/khazhy/redis/redis-stable/src/redis-cli
/home/khazhy/redis/redis-stable/src/redis-cli.c
/home/khazhy/redis/redis-stable/src/redis-cli.o
/home/khazhy/redis/redis-stable/tests/integration/redis-cli.tcl
/usr/local/bin/redis-cli
```

Using `locate redis-cli` seems iffy. In this case, the real binary is the very last item, but the script uses the first item, which is a bash completion script. If redis-cli is on PATH, `which redis-cli` seems better

**Comment by pavelnemirovsky** [comment]
Please check latest changes where if locate didn't find it goes to "default" location. I agree it can be replaced to which, can u PR please.

**Comment by pavelnemirovsky** [comment]
Considered as resolved.
