### ISSUE TITLE
Template import problem

### ISSUE THREAD

**Issue by cricketsamya** [pavelnemirovsky/zabbix-redis-template#9]
Problem with importing template.
Cannot read XML: (41) Specification mandate value for attribute data-pjax-transient [Line: 43 | Column: 89].

**Comment by pavelnemirovsky** [comment]
Hi,
What's your zabbix version?
Please review it looks like very similar https://github.com/adubkov/zbx_nginx_template/issues/4

**Comment by cricketsamya** [comment]
Zabbix 3.0!
But anyways solved! Thanks!
